// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRental.API.Models
{
    [Table("CUSTOMERS")]
    [Index("Cpf", Name = "SYS_C008501", IsUnique = true)]
    public partial class Customer
    {
        public Customer()
        {
            Rentals = new HashSet<Rental>();
        }

        [Key]
        [Column("CUSTOMER_ID", TypeName = "NUMBER(38)")]
        public decimal CustomerId { get; set; }
        [Required]
        [Column("CUSTOMER_NAME")]
        [StringLength(200)]
        [Unicode(false)]
        public string CustomerName { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        [Unicode(false)]
        public string Cpf { get; set; }
        [Required]
        [Column("ADDRESS")]
        [StringLength(200)]
        [Unicode(false)]
        public string Address { get; set; }
        [Required]
        [Column("CITY")]
        [StringLength(100)]
        [Unicode(false)]
        public string City { get; set; }
        [Required]
        [Column("DISTRICT")]
        [StringLength(100)]
        [Unicode(false)]
        public string District { get; set; }
        [Required]
        [Column("PHONE_NUMBER")]
        [StringLength(14)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }

        [InverseProperty("Customer")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}