// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarRental.API.Models
{
    [Table("RENTALS")]
    public partial class Rental
    {
        [Key]
        [Column("RENTAL_ID", TypeName = "NUMBER(38)")]
        public decimal RentalId { get; set; }
        [Column("CUSTOMER_ID", TypeName = "NUMBER(38)")]
        public decimal CustomerId { get; set; }
        [Column("CAR_ID", TypeName = "NUMBER(38)")]
        public decimal CarId { get; set; }
        [Column("RENTAL_DATE", TypeName = "DATE")]
        public DateTime RentalDate { get; set; }
        [Column("RETURN_DATE", TypeName = "DATE")]
        public DateTime ReturnDate { get; set; }
        [Column("TOTAL_PRICE", TypeName = "NUMBER(15,2)")]
        public decimal TotalPrice { get; set; }

        [ForeignKey("CarId")]
        [InverseProperty("Rentals")]
        public virtual Car Car { get; set; }
        [ForeignKey("CustomerId")]
        [InverseProperty("Rentals")]
        public virtual Customer Customer { get; set; }
    }
}