// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarRental.API.Models
{
    [Table("CARS")]
    public partial class Car
    {
        public Car()
        {
            Rentals = new HashSet<Rental>();
        }

        [Key]
        [Column("CAR_ID", TypeName = "NUMBER(38)")]
        public decimal CarId { get; set; }
        [Required]
        [Column("CAR_MODEL")]
        [StringLength(50)]
        [Unicode(false)]
        public string CarModel { get; set; }
        [Required]
        [Column("MANUFACTURER")]
        [StringLength(50)]
        [Unicode(false)]
        public string Manufacturer { get; set; }
        [Required]
        [Column("CAR_TYPE")]
        [StringLength(20)]
        [Unicode(false)]
        public string CarType { get; set; }
        [Required]
        [Column("PLATE")]
        [StringLength(10)]
        [Unicode(false)]
        public string Plate { get; set; }
        [Column("CAR_YEAR", TypeName = "NUMBER(38)")]
        public decimal CarYear { get; set; }
        [Required]
        [Column("COLOR")]
        [StringLength(20)]
        [Unicode(false)]
        public string Color { get; set; }
        [Column("MILEAGE", TypeName = "NUMBER(38)")]
        public decimal Mileage { get; set; }
        [Column("RENT_PRICE", TypeName = "NUMBER(15,2)")]
        public decimal RentPrice { get; set; }

        [InverseProperty("Car")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}